kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        command:
        - hello
        image: quay.io/mhrivnak/hello-service
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: GREETING
            value: Hello

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
